//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int id { get; set; }
        public Nullable<int> id_tov { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<int> id_user { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Users Users { get; set; }
    }
}
